# Taken from here
# https://github.com/Yoshie2000/PlentyChess/blob/main/.github/workflows/plenty.yml
name: Schoenemann Build & Bench
on:
  push:
  workflow_dispatch:
  pull_request:

jobs:
  engine:
    name: Schoenemann Build & Bench
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-24.04, windows-latest]
    
    steps:

    - name: Clone
      uses: actions/checkout@v2

    - name: Compile
      run: cd src && make EXE=Schoenemann

    - name: Bench (Linux/macOS)
      if: runner.os != 'Windows'
      shell: bash
      run: |
        set -euxo pipefail

        git fetch origin "${{ github.event.pull_request.head.ref }}"
        git checkout FETCH_HEAD

        bench=$(git show --summary \
                | grep -oE 'Bench:?[[:space:]][0-9]+' \
                | awk '{print $2}')
        echo "→ expected bench = $bench"

        cd src/
        # Option A: still using a temp file
        ./Schoenemann bench > output
        real=$(grep -E 'Nodes *: ' output | awk '{print $3}')
        echo "→ measured real  = $real"

        # Option B: inline, no temp file
        # real=$(./Schoenemann bench | awk -F'[: ]+' '/Nodes/{print $3}')

        if [[ "$bench" != "$real" ]]; then
          echo "✗ got $real, expected $bench"
          exit 1
        fi

    - name: Bench (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        git fetch origin "${{ github.event.pull_request.head.ref }}"
        git checkout FETCH_HEAD

        $bench = git show --summary `
                 | Select-String -Pattern 'Bench:?\s+\d+' `
                 | ForEach-Object { $_.Matches[0].Groups[1].Value }
        Write-Host "→ expected bench = $bench"

        Set-Location src
        .\Schoenemann bench > output

        # Option A: using the temp file
        $real = Select-String -Path output -Pattern 'Nodes *: ' `
                | ForEach-Object { ($_ -split '\s+')[2] }
        Write-Host "→ measured real  = $real"

        # Option B: inline without temp file
        # $real = .\Schoenemann bench `
        #         | Select-String 'Nodes *: ' `
        #         | ForEach-Object { ($_ -split '\s+')[2] }

        if ($bench -ne $real) {
          Write-Error "✗ got $real, expected $bench"
          exit 1
        }

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: Schoenemann-${{github.sha}}-neon-${{matrix.os}}
        path: src/Schoenemann