# Taken from here
# https://github.com/Yoshie2000/PlentyChess/blob/main/.github/workflows/plenty.yml
name: Schoenemann Build & Bench
on:
  push:
  workflow_dispatch:
  pull_request:

jobs:
  engine:
    name: Schoenemann Build & Bench
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-24.04, windows-latest]
    
    steps:

    - name: Clone
      uses: actions/checkout@v2

    - name: Compile
      run: cd src && make EXE=Schoenemann

    - name: Bench (Linux/macOS)
      if: runner.os != 'Windows'
      shell: bash
      run: |
        set -euxo pipefail

        git fetch origin "${{ github.event.pull_request.head.ref }}"
        git checkout FETCH_HEAD

        bench=$(git show --summary \
                | grep -oE 'Bench:?[[:space:]][0-9]+' \
                | awk '{print $2}')
        echo "→ expected bench = $bench"

        cd src/
        real=$(./Schoenemann bench \
               | awk '/Nodes: /{ print $4 }')
        echo "→ measured real  = $real"

        if [[ "$bench" != "$real" ]]; then
          echo "✗ got $real, expected $bench"
          exit 1
        fi



    - name: Bench (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        # fetch & checkout
        git fetch origin "${{ github.event.pull_request.head.ref }}"
        git checkout FETCH_HEAD

        # extract Bench number (with or without colon)
        $bench = git show --summary |
                 Select-String 'Bench:?\s+[0-9]+' |
                 ForEach-Object { $_.Matches[0].Value -replace '.*\s','' }
        Write-Host "→ expected bench = $bench"

        # run binary and capture real nodes
        Set-Location src
        .\Schoenemann bench > output
        $real = (Select-String -Path output -Pattern 'Nodes: ' |
                 ForEach-Object { ($_ -split '\s+')[3] })
        Write-Host "→ measured real  = $real"

        # fail if they differ
        if ($bench -ne $real) {
          Write-Host "✗ got $real, expected $bench (summary: $(git show --summary))"
          exit 1
        }


    
    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: Schoenemann-${{github.sha}}-neon-${{matrix.os}}
        path: src/Schoenemann