name: Test with Undefined Sanitizer

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install clang++-18 and make
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg lsb-release make
          # Download and run the LLVM installer script to install LLVM 18
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 18
          # Ensure that clang++ points to clang++-18
          sudo ln -sf /usr/bin/clang++-18 /usr/bin/clang++

      - name: Modify Makefile for Undefined Sanitizer
        run: sed -i 's/-fsanitize=memory/-fsanitize=undefined/g' src/Makefile

      - name: Build with make test
        run: |
          cd src
          make test

      - name: Run the test binary
        run: |
          cd src
          ./null bench
