name: Schoenemann Build & Bench
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  engine:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, windows-latest]

    steps:
      - name: Checkout PR head
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 1

      - name: Compile
        run: cd src && make EXE=Schoenemann

      - name: Bench
        shell: ${{ runner.os == 'Windows' && 'pwsh' || 'bash' }}
        run: |
          #— extract expected bench from the commit message
          if (${{ runner.os == 'Windows' }}) {
            $summary = git show --summary
            if ($summary -match 'Bench:?\s+([0-9]+)') {
              $bench = $Matches[1]
            } else {
              Write-Error "No Bench:… in summary:`n$summary"
              exit 1
            }
            Write-Host "→ expected bench = $bench"

            # run and parse real nodes
            Set-Location src
            $out = .\Schoenemann bench
            if ($out -match 'Nodes *: *([0-9]+)') {
              $real = $Matches[1]
            } else {
              Write-Error "No Nodes:… in output:`n$out"
              exit 1
            }
            Write-Host "→ measured real  = $real"

            if ($bench -ne $real) {
              Write-Error "✗ got $real, expected $bench"
              exit 1
            }
          } else {
            set -euxo pipefail
            bench=$(git show --summary \
                    | grep -oE 'Bench:?[[:space:]][0-9]+' \
                    | awk '{print $2}')
            echo "→ expected bench = $bench"
            cd src
            real=$(./Schoenemann bench \
                   | awk -F'[: ]+' '/Nodes/{print $3}')
            echo "→ measured real  = $real"
            if [[ "$bench" != "$real" ]]; then
              echo "✗ got $real, expected $bench"
              exit 1
            fi
          }

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: Schoenemann-${{ matrix.os }}-${{ github.sha }}
          path: src/Schoenemann
