name: Build and Test on Windows and Linux

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup environment
        shell: bash
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            sudo apt-get update
            sudo apt-get install -y --no-install-recommends clang++-18 make wget gnupg lsb-release
            wget https://apt.llvm.org/llvm.sh
            chmod +x llvm.sh
            sudo ./llvm.sh 18
            sudo ln -sf /usr/bin/clang++-18 /usr/bin/clang++
          else
            choco install llvm -y
            choco install make -y
            # Optionally adjust PATH if needed (this example uses the default installation path)
            export PATH="/c/Program Files/LLVM/bin:$PATH"
          fi

      - name: Build with make all
        shell: bash
        run: |
          cd src
          make all
