name: Test with Undefined Sanitizer

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install clang++ and make
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends clang++ make

      - name: Modify Makefile for Undefined Sanitizer
        # Update the sanitizer flag in the Makefile located in the src directory
        run: sed -i 's/-fsanitize=memory/-fsanitize=undefined/g' src/Makefile

      - name: Build with make test
        run: make -C src test

      - name: Run the test binary
        run: ./src/null
